sudo: required

language: minimal

env:
  global:
    - IMAGE=registry.gitlab.com/bleemsync-dev/docker-autodevops-buildenvs/mmc-crosscompiler-docker-image:latest_internal
    - TARGETBUILD=parallel_n64_libretro
  matrix:
    - TARGET=nesc CLOUD_DIR=NESC
    - TARGET=psc CLOUD_DIR=PSC

services:
  - docker

before_script:
  - docker login -u ${GITLAB_USER} -p ${GITLAB_PASS} registry.gitlab.com
  - docker pull ${IMAGE}
  - docker run -it -d --name crosscomp ${IMAGE} bash
  - docker exec -it crosscomp bash -c "git clone --depth=50 --branch=master https://github.com/${TRAVIS_REPO_SLUG} ${TRAVIS_REPO_SLUG}"

script:
  - docker exec -it crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && classic_make_${TARGET} Makefile clean"
  - docker exec -it crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && classic_make_${TARGET} Makefile"
  - docker exec -it crosscomp bash -c "chown 600 ~/.keys/release_private_key.pem"
  - docker exec -it crosscomp bash -c "cd ${TRAVIS_REPO_SLUG} && echo -e  'cd /var/www/html/cores/Automated_Builds/${CLOUD_DIR}\nput ${TARGETBUILD}.so' | sftp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.keys/release_private_key.pem docker@classicmodscloud.com"